version: "3"

services:
  db:
    image: pgvector/pgvector:pg17
    restart: always
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "root1234"
      POSTGRES_DB: "examplesdb"
      POSTGRES_USER: "urstory"
    ports:
      - "5430:5432"

# docker-compose up
